### ISSUE TITLE
AWS Deployment

### ISSUE THREAD

**Issue by aa1588** [aa1588/campusXchange#123]

**Comment by aa1588** [comment]
**Todo:**
- [x] Reset Password Api, Profile Page
- [x] Return Items if Qunatity > 0 from the frontend (Sudin)
- [x] Return Wishlist Items if Quantity > 0 from the frontend (Sudin)
- [ ] Reduce the Quantity of an Item from the Accepted Offer When an itemowner marks an item as sold - then populate the transaction table
- [x] Send Notifications for Questions and Answer Apis
- [ ] Send Notifications for Offer Accepted
- [x] Recommendation UI
- [x] Handle Mail Authentication Exception
- [x] Handle DataIntegrityViolationException (for ex: same phone for signup)
**Problems:**
- [x] Get wishlist Items making infinite db calls (JPA association problem) - fixed: problem was in the frontend useEffeect()

**Comment by aa1588** [comment]
Docker Compose:
-----------------
set MAIL_PASSWORD=your-mail-pass

**infra.yml**
```
---
version: "3.7"
services:
  postgres-db:
    container_name: postgres-campusxchange
    image: postgres
    environment:
      POSTGRES_DB: campusxchange
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-campusxchange:/data/postgres
    ports:
      - "5432:5432"
    restart: always
```

**app.yml**
```
services:
  campusxchange-api:
    container_name: campusxchange-api
    image: campusxchange/campusxchange-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/campusxchange
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_PASSWORD: lnsp qawp llmm jbzn
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres-db

  campusxchange-ui:
    container_name: campusxchange-ui
    build:
      context: ./campusxchange-ui
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://campusxchange-api:8080
    ports:
      - "3000:80" # Serve React on port 3000 through Nginx
    restart: always
    depends_on:
      - campusxchange-api

```

**Comment by aa1588** [comment]
Need to have authToken before connecting to the server for SSE.

```

    useEffect(() => {
        const savedNotifications = localStorage.getItem('notifications')
        if (savedNotifications) {
            setNotifications(JSON.parse(savedNotifications))
        }
        const token: string | undefined = Cookies.get('authToken')
        const eventSourceUrl = `${BACKEND_BASE_URL}/api/notifications/subscribe?token=${token}`

        // Connect to SSE for real-time notifications
        const eventSource = new EventSource(eventSourceUrl)

        // Listen for new notifications
        eventSource.addEventListener('notification', (event) => {
            const newNotification: Notification = JSON.parse(event.data)
            /* Test for SSE-Notification System */

            console.log('New SSE- Notification Received: ', newNotification)

            /* Test for SSE-Notification System */

            // Update state and save to localStorage
            setNotifications((prevState) => {
                const updatedNotifications = [newNotification, ...prevState]
                localStorage.setItem(
                    'notifications',
                    JSON.stringify(updatedNotifications)
                )
                return updatedNotifications
            })

            setUnreadCount((prevCount) => prevCount + 1)
        })

        // Cleanup on component unmount
        return () => {
            eventSource.close()
        }
    }, [])

```

**Comment by aa1588** [comment]
![Image](https://github.com/user-attachments/assets/752e543e-0fcc-4a76-adc3-805082c42b41)
![Image](https://github.com/user-attachments/assets/b1ad6912-e919-44d9-8abe-26753437d16c)
![Image](https://github.com/user-attachments/assets/35f38ac6-554a-4fc0-aede-15eec5f587c5)
![Image](https://github.com/user-attachments/assets/998d1007-4c8e-4ccb-ae75-d75723a2e865)
![Image](https://github.com/user-attachments/assets/b50494f4-0d4f-4011-a799-bc89c4f8b171)

**Comment by aa1588** [comment]
![Image](https://github.com/user-attachments/assets/3dd3c4e7-6f4e-4180-90c1-e01c3b484128)

**Comment by aa1588** [comment]
```
<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<!-- attached to Maven test phase -->
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
